//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVS.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SVS.Strings.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string _acceleration {
            get {
                return ResourceManager.GetString("_acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account：.
        /// </summary>
        internal static string _account {
            get {
                return ResourceManager.GetString("_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice Scores：.
        /// </summary>
        internal static string _adviceScore {
            get {
                return ResourceManager.GetString("_adviceScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string _analysis {
            get {
                return ResourceManager.GetString("_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Screen.
        /// </summary>
        internal static string _clearScreen {
            get {
                return ResourceManager.GetString("_clearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation is complete.
        /// </summary>
        internal static string _confirmComplete {
            get {
                return ResourceManager.GetString("_confirmComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect the pen display with computer.
        /// </summary>
        internal static string _connect {
            get {
                return ResourceManager.GetString("_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to database..
        /// </summary>
        internal static string _connectfail {
            get {
                return ResourceManager.GetString("_connectfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time：.
        /// </summary>
        internal static string _costTime {
            get {
                return ResourceManager.GetString("_costTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account successfully.
        /// </summary>
        internal static string _createAccountSuccess {
            get {
                return ResourceManager.GetString("_createAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score：.
        /// </summary>
        internal static string _currentScore {
            get {
                return ResourceManager.GetString("_currentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string _delete {
            get {
                return ResourceManager.GetString("_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string _deleteAll {
            get {
                return ResourceManager.GetString("_deleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrollment.
        /// </summary>
        internal static string _entrollment {
            get {
                return ResourceManager.GetString("_entrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-Entrollment.
        /// </summary>
        internal static string _entrollmentTitle {
            get {
                return ResourceManager.GetString("_entrollmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string _exit {
            get {
                return ResourceManager.GetString("_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string _fail {
            get {
                return ResourceManager.GetString("_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string _female {
            get {
                return ResourceManager.GetString("_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name：.
        /// </summary>
        internal static string _filename {
            get {
                return ResourceManager.GetString("_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete data.
        /// </summary>
        internal static string _inComplete {
            get {
                return ResourceManager.GetString("_inComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string _info {
            get {
                return ResourceManager.GetString("_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _login {
            get {
                return ResourceManager.GetString("_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success！.
        /// </summary>
        internal static string _loginSuccess {
            get {
                return ResourceManager.GetString("_loginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-Login.
        /// </summary>
        internal static string _loginTitle {
            get {
                return ResourceManager.GetString("_loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string _logout {
            get {
                return ResourceManager.GetString("_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main function.
        /// </summary>
        internal static string _mainFunction {
            get {
                return ResourceManager.GetString("_mainFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string _male {
            get {
                return ResourceManager.GetString("_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Signature.
        /// </summary>
        internal static string _newSignature {
            get {
                return ResourceManager.GetString("_newSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string _pass {
            get {
                return ResourceManager.GetString("_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password：.
        /// </summary>
        internal static string _password {
            get {
                return ResourceManager.GetString("_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string _personalInformation {
            get {
                return ResourceManager.GetString("_personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string _pressure {
            get {
                return ResourceManager.GetString("_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account or password is incorrect. Please try again..
        /// </summary>
        internal static string _relogin {
            get {
                return ResourceManager.GetString("_relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested number of re-signatures.
        /// </summary>
        internal static string _reSignatures {
            get {
                return ResourceManager.GetString("_reSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Range：.
        /// </summary>
        internal static string _scoreRange {
            get {
                return ResourceManager.GetString("_scoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string _sec {
            get {
                return ResourceManager.GetString("_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex：.
        /// </summary>
        internal static string _sex {
            get {
                return ResourceManager.GetString("_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string _shape {
            get {
                return ResourceManager.GetString("_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Score.
        /// </summary>
        internal static string _signatureScore {
            get {
                return ResourceManager.GetString("_signatureScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing the signature is complete.
        /// </summary>
        internal static string _signComplete {
            get {
                return ResourceManager.GetString("_signComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature data error！.
        /// </summary>
        internal static string _signError {
            get {
                return ResourceManager.GetString("_signError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squeezed through.
        /// </summary>
        internal static string _squeezedthrough {
            get {
                return ResourceManager.GetString("_squeezedthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-Signature verification system.
        /// </summary>
        internal static string _svs {
            get {
                return ResourceManager.GetString("_svs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Confirm.
        /// </summary>
        internal static string _templateConfirm {
            get {
                return ResourceManager.GetString("_templateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Selection.
        /// </summary>
        internal static string _templateSelection {
            get {
                return ResourceManager.GetString("_templateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial was expired. Please contact with ViewSonic. Thanks..
        /// </summary>
        internal static string _trialexpired {
            get {
                return ResourceManager.GetString("_trialexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is only licensed to.
        /// </summary>
        internal static string _usererror {
            get {
                return ResourceManager.GetString("_usererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username：.
        /// </summary>
        internal static string _userName {
            get {
                return ResourceManager.GetString("_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string _userSignature {
            get {
                return ResourceManager.GetString("_userSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string _velocity {
            get {
                return ResourceManager.GetString("_velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string _verification {
            get {
                return ResourceManager.GetString("_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerifyCost.
        /// </summary>
        internal static string _verifycost {
            get {
                return ResourceManager.GetString("_verifycost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string _warning {
            get {
                return ResourceManager.GetString("_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
