//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVS.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_tw {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_tw() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SVS.Strings.Resource_zh_tw", typeof(Resource_zh_tw).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度.
        /// </summary>
        internal static string _acceleration {
            get {
                return ResourceManager.GetString("_acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳號：.
        /// </summary>
        internal static string _account {
            get {
                return ResourceManager.GetString("_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建議分數：.
        /// </summary>
        internal static string _adviceScore {
            get {
                return ResourceManager.GetString("_adviceScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簽名分析.
        /// </summary>
        internal static string _analysis {
            get {
                return ResourceManager.GetString("_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除畫面.
        /// </summary>
        internal static string _clearScreen {
            get {
                return ResourceManager.GetString("_clearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認完成.
        /// </summary>
        internal static string _confirmComplete {
            get {
                return ResourceManager.GetString("_confirmComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請連接優派國際電磁筆顯示器.
        /// </summary>
        internal static string _connect {
            get {
                return ResourceManager.GetString("_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法連線到資料庫。.
        /// </summary>
        internal static string _connectfail {
            get {
                return ResourceManager.GetString("_connectfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間：.
        /// </summary>
        internal static string _costTime {
            get {
                return ResourceManager.GetString("_costTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功創建帳戶.
        /// </summary>
        internal static string _createAccountSuccess {
            get {
                return ResourceManager.GetString("_createAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前分數：.
        /// </summary>
        internal static string _currentScore {
            get {
                return ResourceManager.GetString("_currentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        internal static string _delete {
            get {
                return ResourceManager.GetString("_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除資料.
        /// </summary>
        internal static string _deleteAll {
            get {
                return ResourceManager.GetString("_deleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊.
        /// </summary>
        internal static string _entrollment {
            get {
                return ResourceManager.GetString("_entrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-註冊.
        /// </summary>
        internal static string _entrollmentTitle {
            get {
                return ResourceManager.GetString("_entrollmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離開.
        /// </summary>
        internal static string _exit {
            get {
                return ResourceManager.GetString("_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未通過.
        /// </summary>
        internal static string _fail {
            get {
                return ResourceManager.GetString("_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        internal static string _female {
            get {
                return ResourceManager.GetString("_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案名稱：.
        /// </summary>
        internal static string _filename {
            get {
                return ResourceManager.GetString("_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料不完全.
        /// </summary>
        internal static string _inComplete {
            get {
                return ResourceManager.GetString("_inComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資訊.
        /// </summary>
        internal static string _info {
            get {
                return ResourceManager.GetString("_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string _login {
            get {
                return ResourceManager.GetString("_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入成功！.
        /// </summary>
        internal static string _loginSuccess {
            get {
                return ResourceManager.GetString("_loginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-登入系統.
        /// </summary>
        internal static string _loginTitle {
            get {
                return ResourceManager.GetString("_loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string _logout {
            get {
                return ResourceManager.GetString("_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主功能.
        /// </summary>
        internal static string _mainFunction {
            get {
                return ResourceManager.GetString("_mainFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        internal static string _male {
            get {
                return ResourceManager.GetString("_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新筆簽名.
        /// </summary>
        internal static string _newSignature {
            get {
                return ResourceManager.GetString("_newSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無.
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通過.
        /// </summary>
        internal static string _pass {
            get {
                return ResourceManager.GetString("_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼：.
        /// </summary>
        internal static string _password {
            get {
                return ResourceManager.GetString("_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人資料.
        /// </summary>
        internal static string _personalInformation {
            get {
                return ResourceManager.GetString("_personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筆壓.
        /// </summary>
        internal static string _pressure {
            get {
                return ResourceManager.GetString("_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者帳號或密碼錯誤,請再試一次。.
        /// </summary>
        internal static string _relogin {
            get {
                return ResourceManager.GetString("_relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建議重新簽名筆數.
        /// </summary>
        internal static string _reSignatures {
            get {
                return ResourceManager.GetString("_reSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分數範圍：.
        /// </summary>
        internal static string _scoreRange {
            get {
                return ResourceManager.GetString("_scoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string _sec {
            get {
                return ResourceManager.GetString("_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別：.
        /// </summary>
        internal static string _sex {
            get {
                return ResourceManager.GetString("_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外型.
        /// </summary>
        internal static string _shape {
            get {
                return ResourceManager.GetString("_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簽名分數.
        /// </summary>
        internal static string _signatureScore {
            get {
                return ResourceManager.GetString("_signatureScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊簽名完成.
        /// </summary>
        internal static string _signComplete {
            get {
                return ResourceManager.GetString("_signComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簽名數據錯誤！.
        /// </summary>
        internal static string _signError {
            get {
                return ResourceManager.GetString("_signError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勉強通過.
        /// </summary>
        internal static string _squeezedthrough {
            get {
                return ResourceManager.GetString("_squeezedthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-簽名驗證系統.
        /// </summary>
        internal static string _svs {
            get {
                return ResourceManager.GetString("_svs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 樣板確認.
        /// </summary>
        internal static string _templateConfirm {
            get {
                return ResourceManager.GetString("_templateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 樣板挑選.
        /// </summary>
        internal static string _templateSelection {
            get {
                return ResourceManager.GetString("_templateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品已過期,請洽詢 ViewSonic. 謝謝..
        /// </summary>
        internal static string _trialexpired {
            get {
                return ResourceManager.GetString("_trialexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此軟體限定使用者.
        /// </summary>
        internal static string _usererror {
            get {
                return ResourceManager.GetString("_usererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者名稱：.
        /// </summary>
        internal static string _userName {
            get {
                return ResourceManager.GetString("_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者簽名.
        /// </summary>
        internal static string _userSignature {
            get {
                return ResourceManager.GetString("_userSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        internal static string _velocity {
            get {
                return ResourceManager.GetString("_velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驗證.
        /// </summary>
        internal static string _verification {
            get {
                return ResourceManager.GetString("_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比對時間.
        /// </summary>
        internal static string _verifycost {
            get {
                return ResourceManager.GetString("_verifycost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string _warning {
            get {
                return ResourceManager.GetString("_warning", resourceCulture);
            }
        }
    }
}
