//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVS.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SVS.Strings.Resource_zh_cn", typeof(Resource_zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度.
        /// </summary>
        internal static string _acceleration {
            get {
                return ResourceManager.GetString("_acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帐号：.
        /// </summary>
        internal static string _account {
            get {
                return ResourceManager.GetString("_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建议分数：.
        /// </summary>
        internal static string _adviceScore {
            get {
                return ResourceManager.GetString("_adviceScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签名分析.
        /// </summary>
        internal static string _analysis {
            get {
                return ResourceManager.GetString("_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除画面.
        /// </summary>
        internal static string _clearScreen {
            get {
                return ResourceManager.GetString("_clearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认完成.
        /// </summary>
        internal static string _confirmComplete {
            get {
                return ResourceManager.GetString("_confirmComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请连接优派国际电磁笔显示器.
        /// </summary>
        internal static string _connect {
            get {
                return ResourceManager.GetString("_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法连线到资料库。.
        /// </summary>
        internal static string _connectfail {
            get {
                return ResourceManager.GetString("_connectfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间：.
        /// </summary>
        internal static string _costTime {
            get {
                return ResourceManager.GetString("_costTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功创建帐户.
        /// </summary>
        internal static string _createAccountSuccess {
            get {
                return ResourceManager.GetString("_createAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前分数：.
        /// </summary>
        internal static string _currentScore {
            get {
                return ResourceManager.GetString("_currentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string _delete {
            get {
                return ResourceManager.GetString("_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除资料.
        /// </summary>
        internal static string _deleteAll {
            get {
                return ResourceManager.GetString("_deleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string _entrollment {
            get {
                return ResourceManager.GetString("_entrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-注册.
        /// </summary>
        internal static string _entrollmentTitle {
            get {
                return ResourceManager.GetString("_entrollmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离开.
        /// </summary>
        internal static string _exit {
            get {
                return ResourceManager.GetString("_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未通过.
        /// </summary>
        internal static string _fail {
            get {
                return ResourceManager.GetString("_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        internal static string _female {
            get {
                return ResourceManager.GetString("_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案名称：.
        /// </summary>
        internal static string _filename {
            get {
                return ResourceManager.GetString("_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资料不完全.
        /// </summary>
        internal static string _inComplete {
            get {
                return ResourceManager.GetString("_inComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string _info {
            get {
                return ResourceManager.GetString("_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string _login {
            get {
                return ResourceManager.GetString("_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入成功！.
        /// </summary>
        internal static string _loginSuccess {
            get {
                return ResourceManager.GetString("_loginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-登入系統.
        /// </summary>
        internal static string _loginTitle {
            get {
                return ResourceManager.GetString("_loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string _logout {
            get {
                return ResourceManager.GetString("_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主功能.
        /// </summary>
        internal static string _mainFunction {
            get {
                return ResourceManager.GetString("_mainFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        internal static string _male {
            get {
                return ResourceManager.GetString("_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新笔签名.
        /// </summary>
        internal static string _newSignature {
            get {
                return ResourceManager.GetString("_newSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过.
        /// </summary>
        internal static string _pass {
            get {
                return ResourceManager.GetString("_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码：.
        /// </summary>
        internal static string _password {
            get {
                return ResourceManager.GetString("_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人资料.
        /// </summary>
        internal static string _personalInformation {
            get {
                return ResourceManager.GetString("_personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 笔压.
        /// </summary>
        internal static string _pressure {
            get {
                return ResourceManager.GetString("_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者帐号或密码错误,请再试一次。.
        /// </summary>
        internal static string _relogin {
            get {
                return ResourceManager.GetString("_relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建议重新签名笔数.
        /// </summary>
        internal static string _reSignatures {
            get {
                return ResourceManager.GetString("_reSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数范围：.
        /// </summary>
        internal static string _scoreRange {
            get {
                return ResourceManager.GetString("_scoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string _sec {
            get {
                return ResourceManager.GetString("_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性別：.
        /// </summary>
        internal static string _sex {
            get {
                return ResourceManager.GetString("_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外型.
        /// </summary>
        internal static string _shape {
            get {
                return ResourceManager.GetString("_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签名分数.
        /// </summary>
        internal static string _signatureScore {
            get {
                return ResourceManager.GetString("_signatureScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册签名完成.
        /// </summary>
        internal static string _signComplete {
            get {
                return ResourceManager.GetString("_signComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签名数据错误！.
        /// </summary>
        internal static string _signError {
            get {
                return ResourceManager.GetString("_signError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勉强通过.
        /// </summary>
        internal static string _squeezedthrough {
            get {
                return ResourceManager.GetString("_squeezedthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVS-签名验证系统.
        /// </summary>
        internal static string _svs {
            get {
                return ResourceManager.GetString("_svs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样板确认.
        /// </summary>
        internal static string _templateConfirm {
            get {
                return ResourceManager.GetString("_templateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样板挑选.
        /// </summary>
        internal static string _templateSelection {
            get {
                return ResourceManager.GetString("_templateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品已过期,请洽询 ViewSonic. 谢谢..
        /// </summary>
        internal static string _trialexpired {
            get {
                return ResourceManager.GetString("_trialexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此软体限定使用者.
        /// </summary>
        internal static string _usererror {
            get {
                return ResourceManager.GetString("_usererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者名称：.
        /// </summary>
        internal static string _userName {
            get {
                return ResourceManager.GetString("_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者签名.
        /// </summary>
        internal static string _userSignature {
            get {
                return ResourceManager.GetString("_userSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        internal static string _velocity {
            get {
                return ResourceManager.GetString("_velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证.
        /// </summary>
        internal static string _verification {
            get {
                return ResourceManager.GetString("_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比对时间.
        /// </summary>
        internal static string _verifycost {
            get {
                return ResourceManager.GetString("_verifycost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string _warning {
            get {
                return ResourceManager.GetString("_warning", resourceCulture);
            }
        }
    }
}
